# Base configs
baseurl: "z3k3.me/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-115054478-2"

# UI configs
title: "Photography by Astitva Nikose"
subtitle: "Just another photography enthusiast!"
author: "Astitva Nikose"
header:
 title: "Photography"
 subtitle: "by Astitva Nikose"
footer: "&copy; Astitva Nikose 2019"
 name: "Hi I'm Astitva, How you doin?"
 bio: "Techy guy who's also into photography."
 github: "<a href="https://github.com/r3m4g">R3M4G on github</a>"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/astitva.nikose"
  twitter: "https://www.twitter.com/astitva1024"
  instagram: "https://www.instagram.com/colourless.jpg"
  dribbble: 
  linkedin: "https://www.linkedin.com/in/astitva-nikose-341240166"
  github: "https://www.github.com/r3m4g"
